### ISSUE TITLE
Overrides self hosted font

### ISSUE THREAD

**Issue by Jeffrey-Thompson** [bgtdevhub/nearmap-widget#1]
When I import the widget, the self-hosted custom fonts in my other widgets become overridden. widget.css is changing the fonts to Roboto for html/body .

**Comment by fazrulreza** [comment]
Hi @Jeffrey-Thompson , thanks for highlighting this.
We will perform the cleanup necessary for it and keep you updated

**Comment by fazrulreza** [comment]
Hi @Jeffrey-Thompson,

Thanks for the heads up!
Just realized the files you mentioned are the old files used prior to current version.

New version with cleanup done has been deployed

**Comment by fazrulreza** [comment]
Issue fixed in commit [d17c4d9](https://github.com/bgtdevhub/nearmap-widget/commit/d17c4d9ed3f07ed7d092b978606a40fc4928b82a) and [b4713e0](https://github.com/bgtdevhub/nearmap-widget/commit/b4713e00249d966f679c79765f83da160933f75f)
